using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace dataAccess.Entities;

/// <summary>
/// Represents a cached business insight generated by deterministic detectors and AI interpretation.
/// Stored in the AI database for fast retrieval across user sessions.
/// </summary>
[Table("ai_insights")]
public class AiInsight
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Required]
    [Column("business_id")]
    public int BusinessId { get; set; }

    [Required]
    [MaxLength(100)]
    [Column("category")]
    public string Category { get; set; } = string.Empty; // e.g., 'inventory', 'finance', 'sales'

    [Required]
    [MaxLength(100)]
    [Column("detector_version")]
    public string DetectorVersion { get; set; } = string.Empty; // hash/semver of detector bundle

    [Required]
    [Column("raw_findings")]
    public string RawFindings { get; set; } = string.Empty; // JSONB stored as string, contains structured detector output

    [Required]
    [Column("ai_summary")]
    public string AiSummary { get; set; } = string.Empty; // Gemini-generated mentor copy ready for UI

    [Required]
    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [MaxLength(50)]
    [Column("source_event")]
    public string? SourceEvent { get; set; } // e.g., 'login', 'schedule', 'manual_refresh'
}
